### ISSUE TITLE
After Auth0 sign in, viewer not showing restricted datasets

### ISSUE THREAD

**Issue by tiagoams** [dcs4cop/xcube-viewer#149]
Hi,

The behaviour seen is that only unrestricted datsets are listed on the top bar after Auth0 login (scopes are not respected). I tested that the scopes are correct by using the flow for curl on the Auth0 page for the webapp created.
```
curl --request GET \
  --url https://datacube.cefas.co.uk/xcube/datasets \
  --header 'authorization: Bearer <token>
```

This either returns "demo" dataset if correctly authenticated with Client ID and secret or "demoold" if not (see config.yml below).

When I look at the network traffic after the Auth0 login I don't see the viewer requesting data from the API using a token. Shouldn't request 4 have a token?

```
1.
https://dev-h5f1i4sy.eu.auth0.com/u/login?state=<*****>
2.
https://datacube.cefas.co.uk/protected/redirect_uri?code=**************&state=**************
3.
https://datacube.cefas.co.uk/xcube/
4.
https://datacube.cefas.co.uk/xcube/datasets?details=1&tiles=ol4    
```

The setup in .env.local is as follows:

```
REACT_APP_BRANDING=default
REACT_APP_TITLE=xcube Viewer (dev)
REACT_APP_XCUBE_API=https://datacube.cefas.co.uk/xcube
REACT_APP_AUTH0_DOMAIN=https://dev-h5f1i4sy.eu.auth0.com
REACT_APP_AUTH0_CLIENT_ID=**************************************
REACT_APP_AUTH0_AUDIENCE=https://datacube.cefas.co.uk/xcube/
```

config.yml

```
Authentication:
  Domain: dev-h5f1i4sy.eu.auth0.com
  Audience: https://datacube.cefas.co.uk/xcube/

Datasets:
  - Identifier: demo
(...)
    AccessControl:
      RequiredScopes:
       - read:dataset:demo
  - Identifier: demoold
(..)
    AccessControl:
      IsSubstitute: true

```

Version is 0.4.2
commit a2890a7b310ae1d8005dcce10ad4b97e7f67b27a (HEAD, tag: v0.4.2, origin/0.4.x)
