### ISSUE TITLE
Only last configured Identifier is shown in viewer for StoreID: s3 

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#187]
xcube viewer only displays last Identifier served by xcube server when configuring several datasets within a DataStore Identifier. 

I would expect to see all datacube matching any pattern listed as an Identifier. I also tested without wildcards, which does not change the behaviour.  

```
DatasetAttribution:
  - "© by Brockmann Consult GmbH 2020, contains modified Copernicus Data 2019, processed by ESA"
  - "© by EU H2020 CyanoAlert project"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: Sweden
    StoreId: s3
    StoreParams:
      root: water-services/Sweden
      max_depth: 1
      storage_options:
        anon: false
    Datasets:
      - Identifier: "l2c*Sweden*.zarr"
        Style: "default"
      - Identifier: "ws*Sweden*.zarr"
        Style: "default"
```
When adding a new DatStore, with a path to a different bucket, the behaviour persists. Of each DataStore the last configured Dataset Identifier is visible in xcube viewer. 

```
DatasetAttribution:
  - "© by Brockmann Consult GmbH 2020, contains modified Copernicus Data 2019, processed by ESA"
  - "© by EU H2020 CyanoAlert project"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: Sweden
    StoreId: s3
    StoreParams:
      root: water-services/Sweden
      max_depth: 1
      storage_options:
        anon: false
    Datasets:
      - Identifier: "l2c*Sweden*.zarr"
        Style: "default"
      - Identifier: "ws*Sweden*.zarr"
        Style: "default"

DataStores:
  - Identifier: Germany
    StoreId: s3
    StoreParams:
      root: water-services/Germany
      max_depth: 1
      storage_options:
        anon: false
    Datasets:
      - Identifier: "l2c*Germany*.zarr"
        Style: "default"
      - Identifier: "ws*Germany*.zarr"
        Style: "default"
```
